### PR TITLE
46/47/49/108/110

### PR DESCRIPTION
**Pull request by devtsp**
# Summary
- Add responsive page comp at `backoffice/novedades` that displays table of entries and provide delete and edit actions (issues 46/110)  fig1
- Add responsive page comp at `novedades` that displays list of entries using `<News/>` comp (issues 47/110) fig2
- Add responsive page comp that displays detailed view of entry at `novedades/:id` using url params (issues 49/108) fig3
- Update `<Slider/>` comp to match latest projetc style requirements. fig4

# Evidence
### Fig1: issues 46/110
image
### Fig2: issues 47/110
image
### Fig3: issues 49/108
image
### Fig4
image

### CODE REVIEW

**Comment by jovanesDev** [comment]
Hermoso excelente trabajo Tomy , pero dio conflictos

**Comment by devtsp** [comment]
Solucionados los conflictos!!

**Comment by jovanesDev** [comment]
Sigue con conflictos Tomy , ahora en la planning lo vemos

**Comment by devtsp** [comment]
Solved conflicts

**Pull request merged**
